package:
  name: percolation
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit~=2.0
  - numpy
  - matplotlib
  - seaborn
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library provides some useful classes and functions to model percolation
    processes in a 2D on-grid world. '
  dev_url: https://github.com/uibcdf/Percolation
  doc_url: https://uibcdf.org/Percolation
